---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install mysql-server
  apt: name=mysql-server state=present

- name: install python mysql bindings
  apt: name=python-mysqldb state=present
